CREATE TABLE categories
(
	id SERIAL PRIMARY KEY,
	name VARCHAR(256) NOT NULL,
	sort SERIAL UNIQUE,
	description TEXT NOT NULL
);

CREATE TABLE users
(
	id SERIAL PRIMARY KEY,
	username VARCHAR(64) UNIQUE NOT NULL,
	pass_hash CHAR(128) NOT NULL,
	auth_token CHAR(128) NOT NULL,
	date_created TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE threads
(
	id SERIAL PRIMARY KEY,
	name VARCHAR(256) NOT NULL,
	html TEXT NOT NULL,
	raw_text TEXT NOT NULL,
	date_created TIMESTAMP WITH TIME ZONE,

	user_id INTEGER REFERENCES users (id) ON DELETE RESTRICT,
	category_id INTEGER REFERENCES categories (id) ON DELETE RESTRICT
);

CREATE TABLE posts
(
	ID SERIAL PRIMARY KEY,
	html TEXT NOT NULL,
	raw_text TEXT NOT NULL,
	date_created TIMESTAMP WITH TIME ZONE,

	user_id INTEGER REFERENCES users (id) ON DELETE RESTRICT,
	thread_id INTEGER REFERENCES threads (id) ON DELETE RESTRICT
);
